from fastapi import APIRouter, HTTPException
from datetime import datetime, timezone
from core.database import db
from models.project import GitHubPushRequest
from github import Github, GithubException
import asyncio
import logging

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/github", tags=["github"])


@router.post("/push")
async def push_to_github(request: GitHubPushRequest):
    """Push project files to GitHub repository"""
    try:
        g = Github(request.github_token)
        user = g.get_user()
        
        repo = None
        if request.create_repo:
            try:
                repo = user.create_repo(
                    request.repo_name,
                    description=f"Created with AgentForge AI Development Studio",
                    private=False,
                    auto_init=True
                )
                await asyncio.sleep(2)
            except GithubException as e:
                if e.status == 422:
                    repo = user.get_repo(request.repo_name)
                else:
                    raise
        else:
            repo = user.get_repo(request.repo_name)
        
        files = await db.files.find({"project_id": request.project_id}, {"_id": 0}).to_list(500)
        project = await db.projects.find_one({"id": request.project_id}, {"_id": 0})
        
        if not files:
            raise HTTPException(status_code=400, detail="No files to push")
        
        pushed_files = []
        for f in files:
            filepath = f['filepath'].lstrip('/')
            content = f['content']
            
            try:
                existing = repo.get_contents(filepath, ref=request.branch)
                repo.update_file(
                    filepath,
                    request.commit_message,
                    content,
                    existing.sha,
                    branch=request.branch
                )
            except GithubException:
                repo.create_file(
                    filepath,
                    request.commit_message,
                    content,
                    branch=request.branch
                )
            pushed_files.append(filepath)
        
        readme_content = f"""# {project['name']}

{project['description']}

## Project Type
{project['type']} {project.get('engine_version', '')}

## Generated by AgentForge
AI Development Studio - https://agentforge.dev

## Files
{chr(10).join(['- ' + fp for fp in pushed_files])}
"""
        try:
            existing_readme = repo.get_contents("README.md", ref=request.branch)
            repo.update_file("README.md", "Update README", readme_content, existing_readme.sha, branch=request.branch)
        except GithubException:
            repo.create_file("README.md", "Add README", readme_content, branch=request.branch)
        
        await db.projects.update_one(
            {"id": request.project_id},
            {"$set": {"repo_url": repo.html_url, "updated_at": datetime.now(timezone.utc).isoformat()}}
        )
        
        return {
            "success": True,
            "repo_url": repo.html_url,
            "pushed_files": pushed_files,
            "branch": request.branch
        }
        
    except GithubException as e:
        logger.error(f"GitHub error: {e}")
        raise HTTPException(status_code=400, detail=f"GitHub error: {str(e)}")
    except Exception as e:
        logger.error(f"Push error: {e}")
        raise HTTPException(status_code=500, detail=str(e))
